# ---------------------------------------------------------------------------
# Spermatogenesis table button mapping
# ---------------------------------------------------------------------------
# This data-as-code file maps clickable SVG/table button IDs to the stage and
# specific-cell labels used by the precomputed expression matrix. It is sourced
# by server.R at runtime and by build_interactive_assets.R during asset rebuilds.

# Maps spermatogenesis SVG button IDs to stage and cell-type labels. The same
# mapping is used by the runtime modal and the interactive-asset build script.
general_button_mapping <- list(
  "btn_1_1" = list(sample = "I-VI (Weak to Strong)", specificCellID = "El12-13"),
  "btn_1_2" = list(sample = "I-VI (Weak to Strong)", specificCellID = "El14-15"),
  "btn_1_3" = list(sample = "I-VI (Weak to Strong)", specificCellID = "El14-15"),
  "btn_1_4" = list(sample = "I-VI (Weak to Strong)", specificCellID = "El14-15"),
  "btn_1_5" = list(sample = "I-VI (Weak to Strong)", specificCellID = "El14-15"),
  "btn_1_6" = list(sample = "VII-VIII (Dark)", specificCellID = "El16"),
  "btn_1_7" = list(sample = "VII-VIII (Dark)", specificCellID = "El16"),
  "btn_2_1" = list(sample = "I-VI (Weak to Strong)", specificCellID = "Rd1"),
  "btn_2_2" = list(sample = "I-VI (Weak to Strong)", specificCellID = "Rd2-3"),
  "btn_2_3" = list(sample = "I-VI (Weak to Strong)", specificCellID = "Rd4-5"),
  "btn_2_4" = list(sample = "I-VI (Weak to Strong)", specificCellID = "Rd4-5"),
  "btn_2_5" = list(sample = "I-VI (Weak to Strong)", specificCellID = "Rd6"),
  "btn_2_6" = list(sample = "VII-VIII (Dark)", specificCellID = "Rd7"),
  "btn_2_7" = list(sample = "VII-VIII (Dark)", specificCellID = "Rd8"),
  "btn_2_8" = list(sample = "IX-X (Pale)", specificCellID = "El9"),
  "btn_2_9" = list(sample = "IX-X (Pale)", specificCellID = "El9"),
  "btn_2_10" = list(sample = "XI-XII (Pale to Weak)", specificCellID = "El10"),
  "btn_2_11" = list(sample = "XI-XII (Pale to Weak)", specificCellID = "El12-13"),
  "btn_3_1" = list(sample = "I-VI (Weak to Strong)", specificCellID = "PaI-VI"),
  "btn_3_2" = list(sample = "I-VI (Weak to Strong)", specificCellID = "PaI-VI"),
  "btn_3_3" = list(sample = "I-VI (Weak to Strong)", specificCellID = "PaI-VI"),
  "btn_3_4" = list(sample = "I-VI (Weak to Strong)", specificCellID = "PaI-VI"),
  "btn_3_5" = list(sample = "I-VI (Weak to Strong)", specificCellID = "PaI-VI"),
  "btn_3_6" = list(sample = "VII-VIII (Dark)", specificCellID = "PaVII-VIII"),
  "btn_3_7" = list(sample = "VII-VIII (Dark)", specificCellID = "PaVII-VIII"),
  "btn_3_8" = list(sample = "IX-X (Pale)", specificCellID = "PaIX-X"),
  "btn_3_9" = list(sample = "IX-X (Pale)", specificCellID = "PaIX-X"),
  "btn_3_10" = list(sample = "XI-XII (Pale to Weak)", specificCellID = "D/MI"),
  "btn_3_11" = list(sample = "XI-XII (Pale to Weak)", specificCellID = "D/MI"),
  "btn_4_1" = list(sample = "I-VI (Weak to Strong)", specificCellID = "A3-4"),
  "btn_4_2" = list(sample = "I-VI (Weak to Strong)", specificCellID = "Ain"),
  "btn_4_3" = list(sample = "I-VI (Weak to Strong)", specificCellID = "Type B"),
  "btn_4_4" = list(sample = "I-VI (Weak to Strong)", specificCellID = "Type B"),
  "btn_4_5" = list(sample = "I-VI (Weak to Strong)", specificCellID = "ePL"),
  "btn_4_6" = list(sample = "VII-VIII (Dark)", specificCellID = "ePL"),
  "btn_4_7" = list(sample = "VII-VIII (Dark)", specificCellID = "lPL"),
  "btn_4_8" = list(sample = "IX-X (Pale)", specificCellID = "L"),
  "btn_4_9" = list(sample = "IX-X (Pale)", specificCellID = "L/Z"),
  "btn_4_10" = list(sample = "XI-XII (Pale to Weak)", specificCellID = "Z"),
  "btn_4_11" = list(sample = "XI-XII (Pale to Weak)", specificCellID = "Z"),
  "btn_5_1" = list(sample = "I-VI (Weak to Strong)", specificCellID = "Aund"),
  "btn_5_2" = list(sample = "I-VI (Weak to Strong)", specificCellID = "Aund"),
  "btn_5_3" = list(sample = "I-VI (Weak to Strong)", specificCellID = "Aund"),
  "btn_5_4" = list(sample = "I-VI (Weak to Strong)", specificCellID = "Aund"),
  "btn_5_5" = list(sample = "I-VI (Weak to Strong)", specificCellID = "Aund"),
  "btn_5_6" = list(sample = "VII-VIII (Dark)", specificCellID = "A1-2"),
  "btn_5_7" = list(sample = "VII-VIII (Dark)", specificCellID = "A1-2"),
  "btn_5_8" = list(sample = "IX-X (Pale)", specificCellID = "A1-2"),
  "btn_5_9" = list(sample = "IX-X (Pale)", specificCellID = "A1-2"),
  "btn_5_10" = list(sample = "XI-XII (Pale to Weak)", specificCellID = "A3-4"),
  "btn_5_11" = list(sample = "XI-XII (Pale to Weak)", specificCellID = "A3-4"),
  "btn_6_1" = list(sample = "I-VI (Weak to Strong)", specificCellID = "Aund"),
  "btn_6_2" = list(sample = "I-VI (Weak to Strong)", specificCellID = "Aund"),
  "btn_6_3" = list(sample = "I-VI (Weak to Strong)", specificCellID = "Aund"),
  "btn_6_4" = list(sample = "I-VI (Weak to Strong)", specificCellID = "Aund"),
  "btn_6_5" = list(sample = "I-VI (Weak to Strong)", specificCellID = "Aund"),
  "btn_6_6" = list(sample = "VII-VIII (Dark)", specificCellID = "Aund"),
  "btn_6_7" = list(sample = "VII-VIII (Dark)", specificCellID = "Aund"),
  "btn_6_8" = list(sample = "IX-X (Pale)", specificCellID = "Aund"),
  "btn_6_9" = list(sample = "IX-X (Pale)", specificCellID = "Aund"),
  "btn_6_10" = list(sample = "XI-XII (Pale to Weak)", specificCellID = "Aund"),
  "btn_6_11" = list(sample = "XI-XII (Pale to Weak)", specificCellID = "Aund")
)
